//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculApp.Client2.WPF.LineDataServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LineDataServiceReference.ICalculService")]
    public interface ICalculService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculService/Additionner", ReplyAction="http://tempuri.org/ICalculService/AdditionnerResponse")]
        int Additionner(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculService/Additionner", ReplyAction="http://tempuri.org/ICalculService/AdditionnerResponse")]
        System.Threading.Tasks.Task<int> AdditionnerAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculService/Diviser", ReplyAction="http://tempuri.org/ICalculService/DiviserResponse")]
        int Diviser(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculService/Diviser", ReplyAction="http://tempuri.org/ICalculService/DiviserResponse")]
        System.Threading.Tasks.Task<int> DiviserAsync(int a, int b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculServiceChannel : CalculApp.Client2.WPF.LineDataServiceReference.ICalculService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculServiceClient : System.ServiceModel.ClientBase<CalculApp.Client2.WPF.LineDataServiceReference.ICalculService>, CalculApp.Client2.WPF.LineDataServiceReference.ICalculService {
        
        public CalculServiceClient() {
        }
        
        public CalculServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Additionner(int a, int b) {
            return base.Channel.Additionner(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AdditionnerAsync(int a, int b) {
            return base.Channel.AdditionnerAsync(a, b);
        }
        
        public int Diviser(int a, int b) {
            return base.Channel.Diviser(a, b);
        }
        
        public System.Threading.Tasks.Task<int> DiviserAsync(int a, int b) {
            return base.Channel.DiviserAsync(a, b);
        }
    }
}
